"""empty message

Revision ID: 0620dff4bcd0
Revises: 379bc30feb30
Create Date: 2025-03-28 23:30:12.657849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0620dff4bcd0'
down_revision: Union[str, None] = '379bc30feb30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('image_product_id_fkey', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
