"""empty message

Revision ID: 56281fdb4e09
Revises: 74cf4fa312ae
Create Date: 2025-04-04 00:36:51.798836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '56281fdb4e09'
down_revision: Union[str, None] = '74cf4fa312ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))
        batch_op.drop_column('filename')
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###
