"""empty message

Revision ID: 954de0f3254a
Revises: 56281fdb4e09
Create Date: 2025-04-04 00:59:19.034314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '954de0f3254a'
down_revision: Union[str, None] = '56281fdb4e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_index('ix_image_created_at')

    op.drop_table('image')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.create_table('image',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caption', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='image_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_pkey')
    )
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_index('ix_image_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###
